"""Worktree skill materialization contracts."""

import subprocess
from pathlib import Path

import pytest

from spice.agent import lifecycle
from spice.errors import SpiceError


def test_packaged_skill_uses_uniform_spice_command_surface():
    text = lifecycle.packaged_skill_path().read_text(encoding="utf-8")

    assert "using the\n`spice` command directly" in text
    assert "agents should not switch entrypoints" in text
    assert "only as a command-routing marker" in text
    assert "It still goes through `agent run`" in text
    assert "same key=value batch format as task-add batch input" in text
    assert "`TASK title=... | project=<stem.child> | acceptance=...`" in text
    assert "immediate task capture, not allocator selection" in text
    assert "`spice task status` and `spice task doctor` report" in text
    assert "A spice session is a real-time interactive loop" in text
    assert (
        "lead your next working assistant message with a plain-text ACK header" in text
    )
    assert "ACKed keys clear from pending" in text
    assert "Do not bury ACKs mid-message or save them for the final response" in text


def test_available_skill_path_materializes_into_the_worktree(tmp_path):
    located = lifecycle.available_skill_path(tmp_path, required=True)

    expected = tmp_path / lifecycle.WORKTREE_SKILL_RELATIVE_PATH
    ignore = tmp_path / lifecycle.WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH
    assert located == expected.resolve()
    assert located.read_text(
        encoding="utf-8"
    ) == lifecycle.packaged_skill_path().read_text(encoding="utf-8")
    assert ignore.read_text(encoding="utf-8").startswith(
        "# Autogenerated by spice; do not edit.\n"
    )


def test_available_skill_path_required_fails_without_worktree_skill(
    tmp_path, monkeypatch
):
    monkeypatch.setattr(
        lifecycle, "packaged_skill_path", lambda: tmp_path / "missing-package.md"
    )

    with pytest.raises(SpiceError, match="missing spice skill at"):
        lifecycle.available_skill_path(tmp_path, required=True)


def test_materialized_worktree_skill_is_ignored_in_git_repos(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)

    located = lifecycle.available_skill_path(tmp_path, required=True)

    assert located == (tmp_path / lifecycle.WORKTREE_SKILL_RELATIVE_PATH).resolve()
    assert (tmp_path / lifecycle.WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH).read_text(
        encoding="utf-8"
    ) == lifecycle.WORKTREE_SKILL_GITIGNORE_CONTENT
    status = subprocess.run(
        ["git", "-C", str(tmp_path), "status", "--short"],
        check=True,
        capture_output=True,
        text=True,
    )
    assert status.stdout == ""


def test_available_skill_path_leaves_tracked_worktree_skill_clean_when_it_drifts(
    tmp_path,
):
    stale = "---\nname: spice\n---\nrepo-owned skill\n"

    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    subprocess.run(
        ["git", "-C", str(tmp_path), "config", "user.email", "agent@example.test"],
        check=True,
    )
    subprocess.run(
        ["git", "-C", str(tmp_path), "config", "user.name", "Agent"],
        check=True,
    )
    target = tmp_path / lifecycle.WORKTREE_SKILL_RELATIVE_PATH
    target.parent.mkdir(parents=True)
    target.write_text(stale, encoding="utf-8")
    subprocess.run(
        ["git", "-C", str(tmp_path), "add", "--", target.as_posix()], check=True
    )
    subprocess.run(
        ["git", "-C", str(tmp_path), "commit", "-q", "-m", "track worktree skill"],
        check=True,
    )

    located = lifecycle.available_skill_path(tmp_path, required=True)

    assert located == target.resolve()
    assert target.read_text(encoding="utf-8") == stale
    status = subprocess.run(
        ["git", "-C", str(tmp_path), "status", "--short"],
        check=True,
        capture_output=True,
        text=True,
    )
    assert status.stdout == ""


def test_materialize_worktree_skill_refreshes_stale_copies(tmp_path):
    target = tmp_path / lifecycle.WORKTREE_SKILL_RELATIVE_PATH
    target.parent.mkdir(parents=True)
    target.write_text("stale content from an older install\n", encoding="utf-8")

    located = lifecycle.materialize_worktree_skill(tmp_path)

    assert located == target.resolve()
    assert target.read_text(
        encoding="utf-8"
    ) == lifecycle.packaged_skill_path().read_text(encoding="utf-8")


def test_materialize_worktree_skill_leaves_current_copy_untouched(
    tmp_path, monkeypatch
):
    target = tmp_path / lifecycle.WORKTREE_SKILL_RELATIVE_PATH
    target.parent.mkdir(parents=True)
    target.write_text(
        lifecycle.packaged_skill_path().read_text(encoding="utf-8"), encoding="utf-8"
    )
    original_write_text = Path.write_text

    def fail_if_target_is_rewritten(self, *args, **kwargs):
        if self == target:
            raise AssertionError("materialize_worktree_skill rewrote current content")
        return original_write_text(self, *args, **kwargs)

    monkeypatch.setattr(Path, "write_text", fail_if_target_is_rewritten)

    located = lifecycle.materialize_worktree_skill(tmp_path)

    assert located == target.resolve()
