from __future__ import annotations

import stat
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from spice.errors import SpiceError
from spice.hooks import commitmsg, precommit
from spice.hooks.install import hooks_dir, init_repo, install_hooks_for_repo
from tests.test_hookhelpers import (
    _commit,
    _git,
    _git_init,
    _repo_with_pushed_tip,
    _run,
    _write_spice_product_shape,
)


def test_install_hooks_writes_reference_transaction_shim(tmp_path):
    repo = _git_init(tmp_path / "repo")

    rows = install_hooks_for_repo(repo)

    path = hooks_dir(repo) / "reference-transaction"
    assert f"hook reference-transaction -> {path.relative_to(repo).as_posix()}" in rows
    assert path.read_text(encoding="utf-8") == _expected_hook_content(
        'dev reference-transaction "$1"'
    )
    assert path.stat().st_mode & stat.S_IXUSR
    assert (
        _git(repo, "config", "--get", "core.hooksPath").stdout.strip() == ".spice/hooks"
    )


def test_install_hooks_writes_pre_commit_hook_backend_shim(tmp_path):
    repo = _git_init(tmp_path / "repo")

    install_hooks_for_repo(repo)

    content = (hooks_dir(repo) / "pre-commit").read_text(encoding="utf-8")
    assert content == _expected_hook_content("dev pre-commit")


def test_init_repo_reports_generated_worktree_skill_ignore(tmp_path):
    from spice.agent.lifecycle import WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH

    repo = _git_init(tmp_path / "repo")

    rows = init_repo(repo)

    assert f"skill_ignore={WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH.as_posix()}" in rows
    assert (
        (repo / WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH)
        .read_text(encoding="utf-8")
        .startswith("# Autogenerated by spice; do not edit.\n")
    )
    assert _git(repo, "status", "--short").stdout == ""


def test_init_repo_generates_state_gitignore(tmp_path):
    from spice.hooks.install import STATE_GITIGNORE_CONTENT

    repo = _git_init(tmp_path / "repo")

    rows = init_repo(repo)

    assert "state_ignore=.spice/.gitignore" in rows
    assert (repo / ".spice" / ".gitignore").read_text(
        encoding="utf-8"
    ) == STATE_GITIGNORE_CONTENT
    # `.spice/` is excluded by its own generated marker, so init leaves a clean tree.
    assert _git(repo, "status", "--short").stdout == ""


def test_init_repo_keeps_bare_common_linked_worktree_non_bare(tmp_path):
    seed = _git_init(tmp_path / "seed")
    _commit(seed, "README.md", "seed\n", "seed")
    source = tmp_path / "source.git"
    _run(["git", "clone", "--bare", str(seed), str(source)])
    lane = tmp_path / "lane"
    _git(source, "worktree", "add", str(lane), "main")

    rows = init_repo(lane)
    status = _git(lane, "status", "--short")

    assert "core.hooksPath=.spice/hooks" in rows
    assert _git(lane, "config", "--worktree", "--get", "core.bare").stdout.strip() == (
        "false"
    )
    assert _git(lane, "rev-parse", "--is-bare-repository").stdout.strip() == "false"
    assert _git(lane, "rev-parse", "--is-inside-work-tree").stdout.strip() == "true"
    assert status.returncode == 0


def test_init_cli_bootstraps_bare_common_linked_worktree_before_repo_detection(
    tmp_path,
):
    seed = _git_init(tmp_path / "seed")
    _commit(seed, "README.md", "seed\n", "seed")
    source = tmp_path / "source.git"
    _run(["git", "clone", "--bare", str(seed), str(source)])
    lane = tmp_path / "lane"
    _git(source, "worktree", "add", str(lane), "main")

    result = _run([sys.executable, "-m", "spice", "init"], cwd=lane)

    assert result.returncode == 0
    assert "core.hooksPath=.spice/hooks" in result.stdout
    assert _git(lane, "config", "--worktree", "--get", "core.bare").stdout.strip() == (
        "false"
    )
    assert _git(lane, "rev-parse", "--show-toplevel").stdout.strip() == str(lane)
    assert _git(lane, "rev-parse", "--is-inside-work-tree").stdout.strip() == "true"


def test_install_hooks_writes_ambient_spice_shims_for_spice_checkout(tmp_path):
    repo = _git_init(tmp_path / "repo")
    _write_spice_product_shape(repo)

    install_hooks_for_repo(repo)

    assert (hooks_dir(repo) / "reference-transaction").read_text(
        encoding="utf-8"
    ) == _expected_hook_content('dev reference-transaction "$1"')
    assert (hooks_dir(repo) / "commit-msg").read_text(
        encoding="utf-8"
    ) == _expected_hook_content('dev commit-msg "$1"')


def _expected_hook_content(args: str) -> str:
    return (
        "\n".join(["#!/usr/bin/env sh", "", "set -eu", "", f"exec spice {args}"]) + "\n"
    )


def test_reference_transaction_blocks_upstream_merged_current_branch_rewind(tmp_path):
    repo, base, protected = _repo_with_pushed_tip(tmp_path)
    install_hooks_for_repo(repo)

    result = _git(
        repo,
        "update-ref",
        "refs/heads/main",
        base,
        protected,
        check=False,
    )

    assert result.returncode != 0
    assert (
        "reference-transaction guard refused to abandon upstream-merged commits "
        "on current branch refs/heads/main"
    ) in result.stderr
    assert "task boundary has advanced origin/upstream" in result.stderr
    assert "continue with an append-only commit" in result.stderr
    assert _git(repo, "rev-parse", "HEAD").stdout.strip() == protected


def test_reference_transaction_allows_unmerged_current_branch_rewind(tmp_path):
    repo, _, protected = _repo_with_pushed_tip(tmp_path)
    local = _commit(repo, "story.txt", "base\nprotected\nlocal\n", "local work")
    install_hooks_for_repo(repo)

    result = _git(
        repo,
        "update-ref",
        "refs/heads/main",
        protected,
        local,
        check=False,
    )

    assert result.returncode == 0
    assert _git(repo, "rev-parse", "refs/heads/main").stdout.strip() == protected


def test_dev_serve_web_typecheck_parser_exposes_command():
    from spice.cli.parser import build_parser

    args = build_parser().parse_args(["dev", "serve-web-typecheck"])

    assert args.dev_command == "serve-web-typecheck"


def test_dev_pre_commit_parser_exposes_hook_backend_command():
    from spice.cli.parser import build_parser

    args = build_parser().parse_args(["dev", "pre-commit"])

    assert args.dev_command == "pre-commit"
    assert args.pre_commit_args == []


def test_dev_pre_commit_parser_captures_appended_wrapper_arguments():
    from spice.cli.parser import build_parser

    args = build_parser().parse_args(["dev", "pre-commit", "run", "--all-files"])

    assert args.dev_command == "pre-commit"
    assert args.pre_commit_args == ["run", "--all-files"]


def test_dev_pre_commit_runs_gate(tmp_path, monkeypatch):
    from spice.hooks import cli as hooks_cli

    calls: list[Path] = []
    monkeypatch.setattr(hooks_cli, "require_repo_root", lambda: tmp_path)
    monkeypatch.setattr(
        precommit,
        "handle_pre_commit",
        lambda repo_root: calls.append(repo_root) or 0,
    )

    result = hooks_cli.handle_dev(SimpleNamespace(dev_command="pre-commit"))

    assert result == 0
    assert calls == [tmp_path]


def test_dev_pre_commit_reports_repo_gate_replacement_for_upstream_args(
    tmp_path, monkeypatch
):
    from spice.hooks import cli as hooks_cli

    monkeypatch.setattr(hooks_cli, "require_repo_root", lambda: tmp_path)

    with pytest.raises(SpiceError) as exc_info:
        hooks_cli.handle_dev(
            SimpleNamespace(
                dev_command="pre-commit",
                pre_commit_args=["run", "--all-files"],
            )
        )

    message = str(exc_info.value)
    assert "does not accept pre-commit framework arguments: run --all-files" in message
    assert "Run `spice dev pre-commit` for the staged gate" in message


def test_commit_msg_rejects_co_authored_by_trailer(tmp_path):
    message = (
        "Block delegated commit authorship\n"
        "\n"
        "The harness owns the visible commit author contract.\n"
        "\n"
        "Co-Authored-By: Agent <agent@example.test>\n"
    )
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text(message, encoding="utf-8")

    with pytest.raises(SpiceError) as exc_info:
        commitmsg.handle_commit_msg(str(path), tmp_path)

    error = str(exc_info.value)
    assert "forbidden trailer Co-Authored-By" in error
    assert "commit messages must not add co-authors" in error


def test_commit_msg_rejects_wip_subject_and_accepts_real_subject(tmp_path):
    placeholder = tmp_path / "PLACEHOLDER_COMMIT_EDITMSG"
    placeholder.write_text("wip\n", encoding="utf-8")

    with pytest.raises(SpiceError) as exc_info:
        commitmsg.handle_commit_msg(str(placeholder), tmp_path)

    error = str(exc_info.value)
    assert "subject 'wip' is a placeholder" in error
    assert "write a real subject describing the change" in error

    real = tmp_path / "REAL_COMMIT_EDITMSG"
    real.write_text("Block placeholder commit subjects\n", encoding="utf-8")

    assert commitmsg.handle_commit_msg(str(real), tmp_path) == 0


def test_commit_msg_uses_configured_wrap_limit(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        "[tool.spice.policy.limits]\ncommit_message_wrap = 20\n",
        encoding="utf-8",
    )
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text(
        "Hook policy wiring\n\nalpha bravo charlie delta echo foxtrot\n",
        encoding="utf-8",
    )

    assert commitmsg.handle_commit_msg(str(path), tmp_path) == 0

    assert path.read_text(encoding="utf-8").splitlines() == [
        "Hook policy wiring",
        "",
        "alpha bravo charlie",
        "delta echo foxtrot",
    ]


def test_commit_msg_uses_configured_allowed_trailers(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        '[tool.spice.policy.commit_message]\nallowed_trailers = ["Task"]\n',
        encoding="utf-8",
    )
    allowed = tmp_path / "ALLOWED_COMMIT_EDITMSG"
    allowed.write_text(
        "Record task metadata\n\nTask: HOOKS-1\n",
        encoding="utf-8",
    )
    disallowed = tmp_path / "DISALLOWED_COMMIT_EDITMSG"
    disallowed.write_text(
        "Record review metadata\n\nReviewed-By: Agent <agent@example.test>\n",
        encoding="utf-8",
    )

    assert commitmsg.handle_commit_msg(str(allowed), tmp_path) == 0
    with pytest.raises(SpiceError) as exc_info:
        commitmsg.handle_commit_msg(str(disallowed), tmp_path)

    error = str(exc_info.value)
    assert "disallowed trailer reviewed-by" in error
    assert "allowed trailers: task" in error


def test_commit_msg_default_allows_non_forbidden_trailers(tmp_path):
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text(
        "Record review metadata\n\nReviewed-By: Agent <agent@example.test>\n",
        encoding="utf-8",
    )

    assert commitmsg.handle_commit_msg(str(path), tmp_path) == 0


def test_serve_web_typecheck_skips_repo_without_sources(tmp_path, monkeypatch):
    from spice.serve import typecheck

    monkeypatch.setattr(typecheck, "find_tool", lambda name: None)

    assert typecheck.run_serve_web_typecheck(tmp_path) is None


def test_serve_web_typecheck_invokes_typescript_checkjs(tmp_path, monkeypatch):
    from spice.serve import typecheck

    for relative in typecheck.SERVE_WEB_JS_PATHS:
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("// serve static source\n", encoding="utf-8")

    calls = []
    monkeypatch.setattr(typecheck, "find_tool", lambda name: "/usr/bin/npm")

    def fake_run(argv, **kwargs):
        calls.append((argv, kwargs))
        return subprocess.CompletedProcess(argv, 0, "", "")

    monkeypatch.setattr(typecheck.subprocess, "run", fake_run)

    typecheck.run_serve_web_typecheck(tmp_path)

    assert len(calls) == 1
    argv, kwargs = calls[0]
    assert argv[:6] == [
        "/usr/bin/npm",
        "exec",
        "--yes",
        "--package",
        "typescript",
        "tsc",
    ]
    assert "--checkJs" in argv
    assert "--noEmit" in argv
    assert "spice/serve/static/app.types.js" in argv
    assert "spice/serve/static/app.menu.js" in argv
    assert "spice/serve/static/app.js" in argv
    assert kwargs["cwd"] == tmp_path
