"""Side-effect-free discovery and rendering for repository initialization."""

from __future__ import annotations

import hashlib
import json
import stat
from pathlib import Path

from spice.agent.lifecycle import (
    WORKTREE_SKILL_GITIGNORE_CONTENT,
    WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
    WORKTREE_SKILL_RELATIVE_PATH,
    git_tracks_relative_path,
    packaged_skill_path,
)
from spice.config.trust import ExactRepositoryConfigApproval
from spice.errors import SpiceError
from spice.hooks.configapproval import (
    exact_approval_preview_row,
    initialization_command_plan_payload,
)
from spice.hooks.initmodel import (
    InitializationMode,
    InitializationPlan,
    InitOperation,
    InitOperationKind,
    InitOperationScope,
)
from spice.operatorstate import INITIALIZATION_RECEIPT_PATH, operator_state_path
from spice.paths import STATE_DIRNAME, git_common_dir, git_dir
from spice.process.git import run_git_command

HOOKS_DIRNAME = "hooks"
HOOK_ARGS = {
    "pre-commit": "dev pre-commit",
    "commit-msg": 'dev commit-msg "$1"',
    "reference-transaction": 'dev reference-transaction "$1"',
}
GATE_HOOK_ARGS = {
    "pre-commit": HOOK_ARGS["pre-commit"],
    "commit-msg": HOOK_ARGS["commit-msg"],
}
STATE_GITIGNORE_CONTENT = (
    "# Autogenerated by spice; do not edit.\n"
    "# This directory holds machine-local spice state; nothing here is tracked.\n"
    "*\n"
)
HOOKS_PATH = f"{STATE_DIRNAME}/{HOOKS_DIRNAME}"


def hook_shim_content(args: str) -> str:
    return (
        "\n".join(["#!/usr/bin/env sh", "", "set -eu", "", f"exec spice {args}"]) + "\n"
    )


def plan_initialization(
    repo_root: Path,
    mode: InitializationMode | str = InitializationMode.FULL,
    *,
    include_agent_skill: bool = True,
    packaged_skill: Path | None = None,
) -> InitializationPlan:
    """Inspect initialization state without changing files or Git config.

    ``include_agent_skill`` supports the narrower ``dev install-hooks`` repair
    surface while retaining this single planner for every initialization
    operation. Gates-only mode never includes fleet-specific skill assets.
    """
    resolved_root = repo_root.expanduser().resolve()
    normalized_mode = InitializationMode(mode)
    common_config = git_common_dir(resolved_root) / "config"
    worktree_config = git_dir(resolved_root) / "config.worktree"
    operations: list[InitOperation] = [
        _config_operation(
            resolved_root,
            normalized_mode,
            scope=InitOperationScope.COMMON_GIT_CONFIG,
            scope_path=common_config,
            target="extensions.worktreeConfig",
            generated_value="true",
        ),
        _config_operation(
            resolved_root,
            normalized_mode,
            scope=InitOperationScope.WORKTREE_GIT_CONFIG,
            scope_path=worktree_config,
            target="core.bare",
            generated_value="false",
        ),
    ]
    hook_args = (
        GATE_HOOK_ARGS
        if normalized_mode is InitializationMode.GATES_ONLY
        else HOOK_ARGS
    )
    for name, args in hook_args.items():
        operations.append(
            _file_operation(
                resolved_root,
                normalized_mode,
                Path(STATE_DIRNAME) / HOOKS_DIRNAME / name,
                hook_shim_content(args),
                executable=True,
            )
        )
    operations.extend(
        [
            _config_operation(
                resolved_root,
                normalized_mode,
                scope=InitOperationScope.WORKTREE_GIT_CONFIG,
                scope_path=worktree_config,
                target="core.hooksPath",
                generated_value=HOOKS_PATH,
            ),
            _file_operation(
                resolved_root,
                normalized_mode,
                Path(STATE_DIRNAME) / ".gitignore",
                STATE_GITIGNORE_CONTENT,
                new_mode=0o644,
            ),
        ]
    )
    if normalized_mode is InitializationMode.FULL and include_agent_skill:
        source = packaged_skill or packaged_skill_path()
        target = resolved_root / WORKTREE_SKILL_RELATIVE_PATH
        if source.is_file():
            operations.extend(
                [
                    _skill_file_operation(
                        resolved_root,
                        normalized_mode,
                        WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
                        WORKTREE_SKILL_GITIGNORE_CONTENT,
                    ),
                    _skill_file_operation(
                        resolved_root,
                        normalized_mode,
                        WORKTREE_SKILL_RELATIVE_PATH,
                        source.read_text(encoding="utf-8"),
                    ),
                ]
            )
        elif target.is_file():
            operations.append(
                _skill_file_operation(
                    resolved_root,
                    normalized_mode,
                    WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
                    WORKTREE_SKILL_GITIGNORE_CONTENT,
                )
            )
    return InitializationPlan(
        repo_root=resolved_root,
        mode=normalized_mode,
        operations=tuple(operations),
    )


def initialization_plan_payload(
    plan: InitializationPlan,
    *,
    repository_config_approval: ExactRepositoryConfigApproval | None = None,
) -> dict[str, object]:
    """Return the versioned JSON shape consumed by preview clients."""
    return initialization_command_plan_payload(
        repo_root=plan.repo_root,
        mode=plan.mode.value,
        receipt_path=initialization_receipt_path(plan.repo_root),
        operations=tuple(
            {
                **_plan_operation_payload(operation),
                "will_change": operation.will_change,
            }
            for operation in plan.operations
        ),
        approval=repository_config_approval,
    )


def initialization_preview_rows(
    plan: InitializationPlan,
    *,
    repository_config_approval: ExactRepositoryConfigApproval | None = None,
) -> list[str]:
    """Render every ordered file and Git-config transition without mutation."""
    digest = str(
        initialization_plan_payload(
            plan,
            repository_config_approval=repository_config_approval,
        )["plan_digest"]
    )
    rows = [
        f"initialization-plan schema={plan.schema_version} mode={plan.mode.value} "
        f"digest={digest}",
        f"repository={plan.repo_root}",
        f"receipt={initialization_receipt_path(plan.repo_root)}",
    ]
    for index, operation in enumerate(plan.operations, start=1):
        state = (
            "preserve"
            if not operation.managed
            else "change"
            if operation.will_change
            else "ready"
        )
        if operation.kind is InitOperationKind.FILE:
            rows.append(
                f"{index}. file {operation.target} "
                f"mode {_render_mode(operation.previous_mode)} -> "
                f"{_render_mode(operation.generated_mode)} "
                f"digest={operation.ownership_digest} state={state}"
            )
            continue
        effective = ""
        if operation.previous_effective_value != operation.previous_value:
            effective = (
                f" effective={_render_value(operation.previous_effective_value)}"
            )
        rows.append(
            f"{index}. git-config {operation.scope.value} {operation.target} "
            f"at {operation.scope_path}: "
            f"{_render_value(operation.previous_value)} -> "
            f"{_render_value(operation.generated_value)}"
            f"{effective} state={state}"
        )
    if repository_config_approval is not None:
        rows.append(
            exact_approval_preview_row(
                plan.repo_root,
                repository_config_approval,
                order=len(plan.operations) + 1,
            )
        )
    rows.append("preview: no changes applied; pass --apply to execute")
    return rows


def initialization_receipt_path(repo_root: Path) -> Path:
    return operator_state_path(repo_root, INITIALIZATION_RECEIPT_PATH)


def initialization_detail_rows(
    plan: InitializationPlan, *, include_ready: bool
) -> list[str]:
    """Render the stable human detail rows for an applied plan."""
    rows: list[str] = []
    by_target = {operation.target: operation for operation in plan.operations}
    for name in HOOK_ARGS:
        target = f"{HOOKS_PATH}/{name}"
        if target in by_target:
            rows.append(f"hook {name} -> {target}")
    if "core.hooksPath" in by_target:
        rows.append(f"core.hooksPath={HOOKS_PATH}")
    state_ignore = by_target.get(f"{STATE_DIRNAME}/.gitignore")
    if state_ignore is not None and state_ignore.will_change:
        rows.append(f"state_ignore={STATE_DIRNAME}/.gitignore")
    skill = by_target.get(WORKTREE_SKILL_RELATIVE_PATH.as_posix())
    if skill is not None:
        rows.append(f"skill={WORKTREE_SKILL_RELATIVE_PATH.as_posix()}")
    skill_ignore = by_target.get(WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH.as_posix())
    if skill_ignore is not None:
        rows.append(f"skill_ignore={WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH.as_posix()}")
    if include_ready:
        rows.append(
            "ready: git commit | spice dev pre-commit"
            if plan.mode is InitializationMode.GATES_ONLY
            else "ready: spice serve | spice agent ensure | spice task status"
        )
    return rows


def _operation_payload(operation: InitOperation) -> dict[str, object]:
    return {
        "kind": operation.kind.value,
        "target": operation.target,
        "scope": operation.scope.value,
        "scope_path": str(operation.scope_path),
        "previous_value": operation.previous_value,
        "generated_value": operation.generated_value,
        "previous_mode": operation.previous_mode,
        "generated_mode": operation.generated_mode,
        "ownership_digest": operation.ownership_digest,
        "initialization_mode": operation.initialization_mode.value,
        "introduced": operation.introduced,
        "managed": operation.managed,
        "previous_effective_value": operation.previous_effective_value,
        "introduced_parent_directories": list(operation.introduced_parent_directories),
        "introduced_scope_path": operation.introduced_scope_path,
    }


def _plan_operation_payload(operation: InitOperation) -> dict[str, object]:
    return {
        **_operation_payload(operation),
        "observed_before": {
            "value": operation.previous_value,
            "mode": operation.previous_mode,
        },
        "intended_after": {
            "value": operation.generated_value,
            "mode": operation.generated_mode,
        },
    }


def _render_mode(mode: int | None) -> str:
    return "<absent>" if mode is None else f"{mode:04o}"


def _render_value(value: str | None) -> str:
    return "<unset>" if value is None else json.dumps(value)


def _skill_file_operation(
    repo_root: Path,
    mode: InitializationMode,
    relative_path: Path,
    generated_value: str,
) -> InitOperation:
    target = repo_root / relative_path
    managed = True
    if target.is_file():
        previous = target.read_text(encoding="utf-8")
        if previous != generated_value and git_tracks_relative_path(
            repo_root, relative_path
        ):
            managed = False
    return _file_operation(
        repo_root,
        mode,
        relative_path,
        generated_value,
        new_mode=0o600,
        managed=managed,
    )


def _file_operation(
    repo_root: Path,
    mode: InitializationMode,
    relative_path: Path,
    generated_value: str,
    *,
    new_mode: int | None = None,
    executable: bool = False,
    managed: bool = True,
) -> InitOperation:
    target = repo_root / relative_path
    previous_value: str | None
    previous_mode: int | None
    try:
        previous_value = target.read_text(encoding="utf-8")
        previous_mode = stat.S_IMODE(target.stat().st_mode)
    except FileNotFoundError:
        previous_value = None
        previous_mode = None
    generated_mode = previous_mode if previous_mode is not None else new_mode
    if executable:
        generated_mode = (previous_mode or 0o644) | 0o111
    if generated_mode is None:
        raise SpiceError(f"initialization file mode is unresolved for {target}")
    relative = relative_path.as_posix()
    return InitOperation(
        kind=InitOperationKind.FILE,
        target=relative,
        scope=InitOperationScope.WORKTREE_FILE,
        scope_path=repo_root,
        previous_value=previous_value,
        generated_value=generated_value,
        previous_mode=previous_mode,
        generated_mode=generated_mode,
        ownership_digest=_ownership_digest(
            InitOperationKind.FILE,
            InitOperationScope.WORKTREE_FILE,
            relative,
            generated_value,
            generated_mode,
        ),
        initialization_mode=mode,
        introduced=previous_value is None,
        managed=managed,
        introduced_parent_directories=_introduced_parent_directories(
            repo_root, relative_path
        ),
    )


def _config_operation(
    repo_root: Path,
    mode: InitializationMode,
    *,
    scope: InitOperationScope,
    scope_path: Path,
    target: str,
    generated_value: str,
) -> InitOperation:
    previous_value = git_config_file_get(scope_path, target)
    effective = _git_config_get(repo_root, target)
    return InitOperation(
        kind=InitOperationKind.GIT_CONFIG,
        target=target,
        scope=scope,
        scope_path=scope_path,
        previous_value=previous_value,
        generated_value=generated_value,
        previous_mode=None,
        generated_mode=None,
        ownership_digest=_ownership_digest(
            InitOperationKind.GIT_CONFIG,
            scope,
            target,
            generated_value,
            None,
        ),
        initialization_mode=mode,
        introduced=previous_value is None,
        previous_effective_value=effective,
        introduced_scope_path=not _path_exists(scope_path),
    )


def _introduced_parent_directories(
    repo_root: Path, relative_path: Path
) -> tuple[str, ...]:
    introduced: list[str] = []
    parent = relative_path.parent
    while parent != Path("."):
        if not _path_exists(repo_root / parent):
            introduced.append(parent.as_posix())
        parent = parent.parent
    return tuple(reversed(introduced))


def _path_exists(path: Path) -> bool:
    try:
        path.lstat()
    except FileNotFoundError:
        return False
    return True


def _ownership_digest(
    kind: InitOperationKind,
    scope: InitOperationScope,
    target: str,
    generated_value: str,
    generated_mode: int | None,
) -> str:
    payload = json.dumps(
        {
            "generated_mode": generated_mode,
            "generated_value": generated_value,
            "kind": kind.value,
            "scope": scope.value,
            "target": target,
        },
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def git_config_file_get(path: Path, key: str) -> str | None:
    result = run_git_command(
        ["git", "config", "--file", str(path), "--get", key],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode in {0, 1}:
        return result.stdout.strip() or None
    detail = (result.stderr or result.stdout).strip()
    suffix = f": {detail}" if detail else ""
    raise SpiceError(f"could not inspect Git config {path}{suffix}")


def _git_config_get(repo_root: Path, key: str) -> str | None:
    result = run_git_command(
        ["git", "-C", str(repo_root), "config", "--get", key],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode in {0, 1}:
        return result.stdout.strip() or None
    detail = (result.stderr or result.stdout).strip()
    suffix = f": {detail}" if detail else ""
    raise SpiceError(f"could not inspect Git config for {repo_root}{suffix}")
