"""Side-effect-free planning and ordered application for ``spice init``.

The plan is the receipt-shaped boundary between discovery and mutation.  It
captures the exact scoped state observed before initialization and the exact
state Spice intends to generate, including file modes and a deterministic
ownership digest suitable for a later durable receipt.
"""

from __future__ import annotations

import hashlib
import json
import stat
from dataclasses import dataclass, replace
from enum import StrEnum
from pathlib import Path

from spice.agent.lifecycle import (
    WORKTREE_SKILL_GITIGNORE_CONTENT,
    WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
    WORKTREE_SKILL_RELATIVE_PATH,
    git_tracks_relative_path,
    packaged_skill_path,
)
from spice.errors import SpiceError
from spice.paths import STATE_DIRNAME, atomic_write_text, git_common_dir, git_dir
from spice.process.git import run_git_command

HOOKS_DIRNAME = "hooks"
HOOK_ARGS = {
    "pre-commit": "dev pre-commit",
    "commit-msg": 'dev commit-msg "$1"',
    "reference-transaction": 'dev reference-transaction "$1"',
}
GATE_HOOK_ARGS = {
    "pre-commit": HOOK_ARGS["pre-commit"],
    "commit-msg": HOOK_ARGS["commit-msg"],
}
STATE_GITIGNORE_CONTENT = (
    "# Autogenerated by spice; do not edit.\n"
    "# This directory holds machine-local spice state; nothing here is tracked.\n"
    "*\n"
)
HOOKS_PATH = f"{STATE_DIRNAME}/{HOOKS_DIRNAME}"
INIT_RECEIPT_RELATIVE_PATH = Path(STATE_DIRNAME) / "init-receipt.json"
INIT_RECEIPT_MODE = 0o600
DEINIT_RECEIPT_FILENAME = "spice-deinit-receipt.json"
OWNERSHIP_DIGEST_BYTES = 32
FILE_MODE_MAX = 0o7777


class InitializationMode(StrEnum):
    """The operator-visible initialization surface that produced a plan."""

    FULL = "full"
    GATES_ONLY = "gates-only"


class InitOperationKind(StrEnum):
    FILE = "file"
    GIT_CONFIG = "git-config"


class InitOperationScope(StrEnum):
    WORKTREE_FILE = "worktree-file"
    COMMON_GIT_CONFIG = "common-git-config"
    WORKTREE_GIT_CONFIG = "worktree-git-config"


class InitReceiptStatus(StrEnum):
    APPLYING = "applying"
    COMPLETE = "complete"
    DEINITIALIZING = "deinitializing"


@dataclass(frozen=True)
class InitOperation:
    """One fully resolved initialization mutation and its prior provenance."""

    kind: InitOperationKind
    target: str
    scope: InitOperationScope
    scope_path: Path
    previous_value: str | None
    generated_value: str
    previous_mode: int | None
    generated_mode: int | None
    ownership_digest: str
    initialization_mode: InitializationMode
    introduced: bool
    managed: bool = True
    previous_effective_value: str | None = None
    introduced_parent_directories: tuple[str, ...] = ()
    introduced_scope_path: bool = False

    @property
    def will_change(self) -> bool:
        if not self.managed:
            return False
        return (
            self.previous_value != self.generated_value
            or self.previous_mode != self.generated_mode
        )


@dataclass(frozen=True)
class InitializationPlan:
    """A stable, ordered model consumed unchanged by preview and apply."""

    repo_root: Path
    mode: InitializationMode
    operations: tuple[InitOperation, ...]
    schema_version: int = 1


@dataclass(frozen=True)
class InitReceiptOperation:
    """One planned operation plus its durably acknowledged apply state."""

    operation: InitOperation
    completed: bool


@dataclass(frozen=True)
class InitializationReceipt:
    """Machine-local provenance for resumable and reversible initialization."""

    repo_root: Path
    mode: InitializationMode
    plan_schema_version: int
    status: InitReceiptStatus
    operations: tuple[InitReceiptOperation, ...]
    schema_version: int = 1


def hook_shim_content(args: str) -> str:
    return (
        "\n".join(["#!/usr/bin/env sh", "", "set -eu", "", f"exec spice {args}"]) + "\n"
    )


def plan_initialization(
    repo_root: Path,
    mode: InitializationMode | str = InitializationMode.FULL,
    *,
    include_agent_skill: bool = True,
    packaged_skill: Path | None = None,
) -> InitializationPlan:
    """Inspect initialization state without changing files or Git config.

    ``include_agent_skill`` supports the narrower ``dev install-hooks`` repair
    surface while retaining this single planner for every initialization
    operation.  Gates-only mode never includes fleet-specific skill assets.
    """
    resolved_root = repo_root.expanduser().resolve()
    normalized_mode = InitializationMode(mode)
    common_config = git_common_dir(resolved_root) / "config"
    worktree_config = git_dir(resolved_root) / "config.worktree"
    operations: list[InitOperation] = [
        _config_operation(
            resolved_root,
            normalized_mode,
            scope=InitOperationScope.COMMON_GIT_CONFIG,
            scope_path=common_config,
            target="extensions.worktreeConfig",
            generated_value="true",
        ),
        _config_operation(
            resolved_root,
            normalized_mode,
            scope=InitOperationScope.WORKTREE_GIT_CONFIG,
            scope_path=worktree_config,
            target="core.bare",
            generated_value="false",
        ),
    ]
    hook_args = (
        GATE_HOOK_ARGS
        if normalized_mode is InitializationMode.GATES_ONLY
        else HOOK_ARGS
    )
    for name, args in hook_args.items():
        operations.append(
            _file_operation(
                resolved_root,
                normalized_mode,
                Path(STATE_DIRNAME) / HOOKS_DIRNAME / name,
                hook_shim_content(args),
                executable=True,
            )
        )
    operations.extend(
        [
            _config_operation(
                resolved_root,
                normalized_mode,
                scope=InitOperationScope.WORKTREE_GIT_CONFIG,
                scope_path=worktree_config,
                target="core.hooksPath",
                generated_value=HOOKS_PATH,
            ),
            _file_operation(
                resolved_root,
                normalized_mode,
                Path(STATE_DIRNAME) / ".gitignore",
                STATE_GITIGNORE_CONTENT,
                new_mode=0o644,
            ),
        ]
    )
    if normalized_mode is InitializationMode.FULL and include_agent_skill:
        source = packaged_skill or packaged_skill_path()
        target = resolved_root / WORKTREE_SKILL_RELATIVE_PATH
        if source.is_file():
            operations.extend(
                [
                    _skill_file_operation(
                        resolved_root,
                        normalized_mode,
                        WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
                        WORKTREE_SKILL_GITIGNORE_CONTENT,
                    ),
                    _skill_file_operation(
                        resolved_root,
                        normalized_mode,
                        WORKTREE_SKILL_RELATIVE_PATH,
                        source.read_text(encoding="utf-8"),
                    ),
                ]
            )
        elif target.is_file():
            operations.append(
                _skill_file_operation(
                    resolved_root,
                    normalized_mode,
                    WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH,
                    WORKTREE_SKILL_GITIGNORE_CONTENT,
                )
            )
    return InitializationPlan(
        repo_root=resolved_root,
        mode=normalized_mode,
        operations=tuple(operations),
    )


def initialization_plan_payload(plan: InitializationPlan) -> dict[str, object]:
    """Return the versioned JSON shape consumed by preview clients."""
    return {
        "schema_version": plan.schema_version,
        "repository": str(plan.repo_root),
        "mode": plan.mode.value,
        "receipt_path": INIT_RECEIPT_RELATIVE_PATH.as_posix(),
        "operations": [
            {
                "order": order,
                **_operation_payload(operation),
                "will_change": operation.will_change,
            }
            for order, operation in enumerate(plan.operations, start=1)
        ],
    }


def initialization_preview_rows(plan: InitializationPlan) -> list[str]:
    """Render every ordered file and Git-config transition without mutation."""
    rows = [
        f"initialization-plan schema={plan.schema_version} mode={plan.mode.value}",
        f"repository={plan.repo_root}",
        f"receipt={INIT_RECEIPT_RELATIVE_PATH.as_posix()}",
    ]
    for index, operation in enumerate(plan.operations, start=1):
        state = (
            "preserve"
            if not operation.managed
            else "change"
            if operation.will_change
            else "ready"
        )
        if operation.kind is InitOperationKind.FILE:
            rows.append(
                f"{index}. file {operation.target} "
                f"mode {_render_mode(operation.previous_mode)} -> "
                f"{_render_mode(operation.generated_mode)} "
                f"digest={operation.ownership_digest} state={state}"
            )
            continue
        effective = ""
        if operation.previous_effective_value != operation.previous_value:
            effective = (
                f" effective={_render_value(operation.previous_effective_value)}"
            )
        rows.append(
            f"{index}. git-config {operation.scope.value} {operation.target} "
            f"at {operation.scope_path}: "
            f"{_render_value(operation.previous_value)} -> "
            f"{_render_value(operation.generated_value)}"
            f"{effective} state={state}"
        )
    rows.append("preview: no changes applied; pass --apply to execute")
    return rows


def initialization_receipt_path(repo_root: Path) -> Path:
    return repo_root.expanduser().resolve() / INIT_RECEIPT_RELATIVE_PATH


def initialization_receipt_payload(
    receipt: InitializationReceipt,
) -> dict[str, object]:
    return {
        "schema_version": receipt.schema_version,
        "plan_schema_version": receipt.plan_schema_version,
        "repository": str(receipt.repo_root),
        "mode": receipt.mode.value,
        "status": receipt.status.value,
        "operations": [
            {
                **_operation_payload(receipt_operation.operation),
                "completed": receipt_operation.completed,
            }
            for receipt_operation in receipt.operations
        ],
    }


def load_initialization_receipt(repo_root: Path) -> InitializationReceipt | None:
    path = initialization_receipt_path(repo_root)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None
    except (OSError, json.JSONDecodeError) as exc:
        raise SpiceError(
            f"could not read initialization receipt {path}: {exc}"
        ) from exc
    try:
        return initialization_receipt_from_payload(payload)
    except (KeyError, TypeError, ValueError) as exc:
        raise SpiceError(f"invalid initialization receipt {path}: {exc}") from exc


def apply_initialization_plan(plan: InitializationPlan) -> InitializationReceipt:
    """Apply one plan with an atomically updated receipt after every operation."""
    if (git_dir(plan.repo_root) / DEINIT_RECEIPT_FILENAME).is_file():
        raise SpiceError(
            "run `spice deinit` to resume the interrupted deinitialization; "
            "initialization cannot run while its receipt is active"
        )
    existing = load_initialization_receipt(plan.repo_root)
    if existing is not None and existing.status is InitReceiptStatus.DEINITIALIZING:
        raise SpiceError(
            "run `spice deinit` to resume the interrupted deinitialization; "
            "initialization cannot run while its receipt is active"
        )
    receipt = _receipt_for_plan(plan, existing)
    plan_by_key = {
        _operation_key(operation): operation for operation in plan.operations
    }
    if len(plan_by_key) != len(plan.operations):
        raise SpiceError("initialization plan contains duplicate operation identities")
    candidate_operations = tuple(
        replace(receipt_operation, completed=True)
        if _operation_key(receipt_operation.operation) in plan_by_key
        else receipt_operation
        for receipt_operation in receipt.operations
    )
    completed_candidate = replace(
        receipt,
        status=(
            InitReceiptStatus.COMPLETE
            if all(operation.completed for operation in candidate_operations)
            else InitReceiptStatus.APPLYING
        ),
        operations=candidate_operations,
    )
    if (
        existing is not None
        and existing == completed_candidate
        and all(not operation.will_change for operation in plan.operations)
    ):
        return existing

    write_initialization_receipt(receipt)
    operations = list(receipt.operations)
    positions = {
        _operation_key(receipt_operation.operation): index
        for index, receipt_operation in enumerate(operations)
    }
    for operation in plan.operations:
        position = positions[_operation_key(operation)]
        if operation.will_change:
            if operation.kind is InitOperationKind.FILE:
                _apply_file_operation(plan.repo_root, operation)
            else:
                _apply_config_operation(plan.repo_root, operation)
        if not operations[position].completed:
            operations[position] = replace(operations[position], completed=True)
            receipt = replace(receipt, operations=tuple(operations))
            write_initialization_receipt(receipt)

    status = (
        InitReceiptStatus.COMPLETE
        if all(operation.completed for operation in operations)
        else InitReceiptStatus.APPLYING
    )
    receipt = replace(receipt, status=status, operations=tuple(operations))
    write_initialization_receipt(receipt)
    return receipt


def initialization_detail_rows(
    plan: InitializationPlan, *, include_ready: bool
) -> list[str]:
    """Render the stable human detail rows for an applied plan."""
    rows: list[str] = []
    by_target = {operation.target: operation for operation in plan.operations}
    for name in HOOK_ARGS:
        target = f"{HOOKS_PATH}/{name}"
        if target in by_target:
            rows.append(f"hook {name} -> {target}")
    if "core.hooksPath" in by_target:
        rows.append(f"core.hooksPath={HOOKS_PATH}")
    state_ignore = by_target.get(f"{STATE_DIRNAME}/.gitignore")
    if state_ignore is not None and state_ignore.will_change:
        rows.append(f"state_ignore={STATE_DIRNAME}/.gitignore")
    skill = by_target.get(WORKTREE_SKILL_RELATIVE_PATH.as_posix())
    if skill is not None:
        rows.append(f"skill={WORKTREE_SKILL_RELATIVE_PATH.as_posix()}")
    skill_ignore = by_target.get(WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH.as_posix())
    if skill_ignore is not None:
        rows.append(f"skill_ignore={WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH.as_posix()}")
    if include_ready:
        rows.append(
            "ready: git commit | spice dev pre-commit"
            if plan.mode is InitializationMode.GATES_ONLY
            else "ready: spice serve | spice agent ensure | spice task status"
        )
    return rows


def _operation_payload(operation: InitOperation) -> dict[str, object]:
    return {
        "kind": operation.kind.value,
        "target": operation.target,
        "scope": operation.scope.value,
        "scope_path": str(operation.scope_path),
        "previous_value": operation.previous_value,
        "generated_value": operation.generated_value,
        "previous_mode": operation.previous_mode,
        "generated_mode": operation.generated_mode,
        "ownership_digest": operation.ownership_digest,
        "initialization_mode": operation.initialization_mode.value,
        "introduced": operation.introduced,
        "managed": operation.managed,
        "previous_effective_value": operation.previous_effective_value,
        "introduced_parent_directories": list(operation.introduced_parent_directories),
        "introduced_scope_path": operation.introduced_scope_path,
    }


def _optional_string(value: object) -> str | None:
    if value is None or isinstance(value, str):
        return value
    raise TypeError("value must be a string or null")


def _required_string(value: object) -> str:
    if isinstance(value, str):
        return value
    raise TypeError("value must be a string")


def _optional_mode(value: object) -> int | None:
    if value is None:
        return None
    if (
        isinstance(value, int)
        and not isinstance(value, bool)
        and 0 <= value <= FILE_MODE_MAX
    ):
        return value
    raise TypeError("file mode must be an integer from 0 through 07777 or null")


def _required_bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    raise TypeError("value must be boolean")


def _required_int(value: object) -> int:
    if isinstance(value, int) and not isinstance(value, bool):
        return value
    raise TypeError("value must be an integer")


def _string_tuple(value: object) -> tuple[str, ...]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise TypeError("value must be a list of strings")
    return tuple(value)


def _required_ownership_digest(value: object) -> str:
    digest = _required_string(value)
    try:
        decoded = bytes.fromhex(digest)
    except ValueError as exc:
        raise TypeError("ownership digest must be hexadecimal SHA-256") from exc
    if len(decoded) != OWNERSHIP_DIGEST_BYTES:
        raise TypeError("ownership digest must be hexadecimal SHA-256")
    return digest


def _operation_from_payload(payload: dict[str, object]) -> InitOperation:
    return InitOperation(
        kind=InitOperationKind(_required_string(payload["kind"])),
        target=_required_string(payload["target"]),
        scope=InitOperationScope(_required_string(payload["scope"])),
        scope_path=Path(_required_string(payload["scope_path"])),
        previous_value=_optional_string(payload.get("previous_value")),
        generated_value=_required_string(payload["generated_value"]),
        previous_mode=_optional_mode(payload.get("previous_mode")),
        generated_mode=_optional_mode(payload.get("generated_mode")),
        ownership_digest=_required_ownership_digest(payload["ownership_digest"]),
        initialization_mode=InitializationMode(
            _required_string(payload["initialization_mode"])
        ),
        introduced=_required_bool(payload["introduced"]),
        managed=_required_bool(payload["managed"]),
        previous_effective_value=_optional_string(
            payload.get("previous_effective_value")
        ),
        introduced_parent_directories=_string_tuple(
            payload.get("introduced_parent_directories", [])
        ),
        introduced_scope_path=_required_bool(
            payload.get("introduced_scope_path", False)
        ),
    )


def initialization_receipt_from_payload(
    payload: dict[str, object],
) -> InitializationReceipt:
    if payload["schema_version"] != 1:
        raise ValueError(f"unsupported schema version {payload['schema_version']!r}")
    plan_schema_version = _required_int(payload["plan_schema_version"])
    if plan_schema_version != 1:
        raise ValueError(f"unsupported plan schema version {plan_schema_version!r}")
    operation_payloads = payload["operations"]
    if not isinstance(operation_payloads, list):
        raise TypeError("operations must be a list")
    operations: list[InitReceiptOperation] = []
    operation_keys: set[tuple[InitOperationKind, InitOperationScope, str]] = set()
    for item in operation_payloads:
        if not isinstance(item, dict):
            raise TypeError("receipt operation must be an object")
        completed = item.get("completed")
        if not isinstance(completed, bool):
            raise TypeError("receipt operation completion must be boolean")
        receipt_operation = InitReceiptOperation(
            operation=_operation_from_payload(item),
            completed=completed,
        )
        key = _operation_key(receipt_operation.operation)
        if key in operation_keys:
            raise ValueError(f"duplicate receipt operation identity {key!r}")
        operation_keys.add(key)
        operations.append(receipt_operation)
    status = InitReceiptStatus(_required_string(payload["status"]))
    if status is InitReceiptStatus.COMPLETE and any(
        not operation.completed for operation in operations
    ):
        raise ValueError("complete receipt contains unfinished operations")
    return InitializationReceipt(
        repo_root=Path(_required_string(payload["repository"])).expanduser().resolve(),
        mode=InitializationMode(_required_string(payload["mode"])),
        plan_schema_version=plan_schema_version,
        status=status,
        operations=tuple(operations),
        schema_version=_required_int(payload["schema_version"]),
    )


def _operation_key(
    operation: InitOperation,
) -> tuple[InitOperationKind, InitOperationScope, str]:
    return operation.kind, operation.scope, operation.target


def _receipt_for_plan(
    plan: InitializationPlan,
    existing: InitializationReceipt | None,
) -> InitializationReceipt:
    if existing is None:
        return InitializationReceipt(
            repo_root=plan.repo_root,
            mode=plan.mode,
            plan_schema_version=plan.schema_version,
            status=InitReceiptStatus.APPLYING,
            operations=tuple(
                InitReceiptOperation(operation=operation, completed=False)
                for operation in plan.operations
            ),
        )
    if existing.repo_root != plan.repo_root:
        raise SpiceError(
            "initialization receipt belongs to a different repository: "
            f"{existing.repo_root}"
        )

    planned_by_key = {
        _operation_key(operation): operation for operation in plan.operations
    }
    merged: list[InitReceiptOperation] = []
    seen: set[tuple[InitOperationKind, InitOperationScope, str]] = set()
    for receipt_operation in existing.operations:
        key = _operation_key(receipt_operation.operation)
        planned = planned_by_key.get(key)
        if planned is None:
            merged.append(receipt_operation)
        else:
            merged.append(_merge_receipt_operation(receipt_operation, planned))
            seen.add(key)
    for operation in plan.operations:
        key = _operation_key(operation)
        if key in seen:
            continue
        merged.append(InitReceiptOperation(operation=operation, completed=False))

    mode = (
        InitializationMode.FULL
        if InitializationMode.FULL in {existing.mode, plan.mode}
        else InitializationMode.GATES_ONLY
    )
    return InitializationReceipt(
        repo_root=plan.repo_root,
        mode=mode,
        plan_schema_version=plan.schema_version,
        status=InitReceiptStatus.APPLYING,
        operations=tuple(merged),
    )


def _merge_receipt_operation(
    existing: InitReceiptOperation,
    planned: InitOperation,
) -> InitReceiptOperation:
    previous = existing.operation
    operation = replace(
        planned,
        previous_value=previous.previous_value,
        previous_mode=previous.previous_mode,
        initialization_mode=previous.initialization_mode,
        introduced=previous.introduced,
        previous_effective_value=previous.previous_effective_value,
        introduced_parent_directories=previous.introduced_parent_directories,
        introduced_scope_path=previous.introduced_scope_path,
    )
    completed = (
        existing.completed
        and previous.ownership_digest == planned.ownership_digest
        and not planned.will_change
    )
    return InitReceiptOperation(operation=operation, completed=completed)


def write_initialization_receipt(receipt: InitializationReceipt) -> None:
    path = initialization_receipt_path(receipt.repo_root)
    content = (
        json.dumps(
            initialization_receipt_payload(receipt),
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    atomic_write_text(path, content, write_if_changed=True)
    path.chmod(INIT_RECEIPT_MODE)


def _render_mode(mode: int | None) -> str:
    return "<absent>" if mode is None else f"{mode:04o}"


def _render_value(value: str | None) -> str:
    return "<unset>" if value is None else json.dumps(value)


def _skill_file_operation(
    repo_root: Path,
    mode: InitializationMode,
    relative_path: Path,
    generated_value: str,
) -> InitOperation:
    target = repo_root / relative_path
    managed = True
    if target.is_file():
        previous = target.read_text(encoding="utf-8")
        if previous != generated_value and git_tracks_relative_path(
            repo_root, relative_path
        ):
            managed = False
    return _file_operation(
        repo_root,
        mode,
        relative_path,
        generated_value,
        new_mode=0o600,
        managed=managed,
    )


def _file_operation(
    repo_root: Path,
    mode: InitializationMode,
    relative_path: Path,
    generated_value: str,
    *,
    new_mode: int | None = None,
    executable: bool = False,
    managed: bool = True,
) -> InitOperation:
    target = repo_root / relative_path
    previous_value: str | None
    previous_mode: int | None
    try:
        previous_value = target.read_text(encoding="utf-8")
        previous_mode = stat.S_IMODE(target.stat().st_mode)
    except FileNotFoundError:
        previous_value = None
        previous_mode = None
    generated_mode = previous_mode if previous_mode is not None else new_mode
    if executable:
        generated_mode = (previous_mode or 0o644) | 0o111
    if generated_mode is None:
        raise SpiceError(f"initialization file mode is unresolved for {target}")
    relative = relative_path.as_posix()
    return InitOperation(
        kind=InitOperationKind.FILE,
        target=relative,
        scope=InitOperationScope.WORKTREE_FILE,
        scope_path=repo_root,
        previous_value=previous_value,
        generated_value=generated_value,
        previous_mode=previous_mode,
        generated_mode=generated_mode,
        ownership_digest=_ownership_digest(
            InitOperationKind.FILE,
            InitOperationScope.WORKTREE_FILE,
            relative,
            generated_value,
            generated_mode,
        ),
        initialization_mode=mode,
        introduced=previous_value is None,
        managed=managed,
        introduced_parent_directories=_introduced_parent_directories(
            repo_root, relative_path
        ),
    )


def _config_operation(
    repo_root: Path,
    mode: InitializationMode,
    *,
    scope: InitOperationScope,
    scope_path: Path,
    target: str,
    generated_value: str,
) -> InitOperation:
    previous_value = git_config_file_get(scope_path, target)
    effective = _git_config_get(repo_root, target)
    return InitOperation(
        kind=InitOperationKind.GIT_CONFIG,
        target=target,
        scope=scope,
        scope_path=scope_path,
        previous_value=previous_value,
        generated_value=generated_value,
        previous_mode=None,
        generated_mode=None,
        ownership_digest=_ownership_digest(
            InitOperationKind.GIT_CONFIG,
            scope,
            target,
            generated_value,
            None,
        ),
        initialization_mode=mode,
        introduced=previous_value is None,
        previous_effective_value=effective,
        introduced_scope_path=not _path_exists(scope_path),
    )


def _introduced_parent_directories(
    repo_root: Path, relative_path: Path
) -> tuple[str, ...]:
    introduced: list[str] = []
    parent = relative_path.parent
    while parent != Path("."):
        if not _path_exists(repo_root / parent):
            introduced.append(parent.as_posix())
        parent = parent.parent
    return tuple(reversed(introduced))


def _path_exists(path: Path) -> bool:
    try:
        path.lstat()
    except FileNotFoundError:
        return False
    return True


def _ownership_digest(
    kind: InitOperationKind,
    scope: InitOperationScope,
    target: str,
    generated_value: str,
    generated_mode: int | None,
) -> str:
    payload = json.dumps(
        {
            "generated_mode": generated_mode,
            "generated_value": generated_value,
            "kind": kind.value,
            "scope": scope.value,
            "target": target,
        },
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def git_config_file_get(path: Path, key: str) -> str | None:
    result = run_git_command(
        ["git", "config", "--file", str(path), "--get", key],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode in {0, 1}:
        return result.stdout.strip() or None
    detail = (result.stderr or result.stdout).strip()
    suffix = f": {detail}" if detail else ""
    raise SpiceError(f"could not inspect Git config {path}{suffix}")


def _git_config_get(repo_root: Path, key: str) -> str | None:
    result = run_git_command(
        ["git", "-C", str(repo_root), "config", "--get", key],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode in {0, 1}:
        return result.stdout.strip() or None
    detail = (result.stderr or result.stdout).strip()
    suffix = f": {detail}" if detail else ""
    raise SpiceError(f"could not inspect Git config for {repo_root}{suffix}")


def _apply_file_operation(repo_root: Path, operation: InitOperation) -> None:
    target = repo_root / operation.target
    atomic_write_text(target, operation.generated_value, write_if_changed=True)
    if operation.generated_mode is not None:
        target.chmod(operation.generated_mode)


def _apply_config_operation(repo_root: Path, operation: InitOperation) -> None:
    if operation.scope is InitOperationScope.COMMON_GIT_CONFIG:
        args = ["config", operation.target, operation.generated_value]
    else:
        args = [
            "config",
            "--worktree",
            operation.target,
            operation.generated_value,
        ]
    result = run_git_command(
        ["git", "-C", str(repo_root), *args],
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode == 0:
        return
    detail = (result.stderr or result.stdout).strip()
    suffix = f": {detail}" if detail else ""
    raise SpiceError(
        f"could not apply initialization Git config {operation.target} "
        f"for {repo_root}{suffix}"
    )
