"""Per-process lane self-tracking, injected into agent git environments only.

An agent's branch should track *itself* so its ``git status`` never moves when
origin advances — but the operator working in the same repo must still see the
real upstream. So the mask is environment-only (never written to shared config):

* ``GIT_CONFIG_SYSTEM`` points git at a generated per-lane file holding
  ``branch.<lane>.merge = refs/heads/<lane>``. System config is read *first*, and
  ``@{upstream}`` uses the *first* ``branch.merge`` value, so the agent's upstream
  resolves to itself. (The native ``merge`` stays last, so ``git config --get``
  still returns the real branch — the control plane reads truth.)
* a command-scope ``branch.<lane>.remote=.`` pair (read *last*, where ``remote``
  is resolved) completes the self-reference.

The operator runs without these vars and sees the real upstream untouched. The
task control plane reads the integration baseline from ``origin/HEAD`` (see
``spice.tasks.gitsync``), which is independent of branch config, so it needs no
scrubbing.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path

AGENT_SELF_TRACKING_CONFIG_NAME = "agent-self-tracking.gitconfig"


def agent_self_tracking_environment(
    repo_root: Path | None, *, base_env: Mapping[str, str] | None = None
) -> dict[str, str]:
    env = dict(os.environ if base_env is None else base_env)
    branch = current_git_branch(repo_root)
    if repo_root is None or not branch:
        return env
    config_path = write_agent_self_tracking_config(repo_root, branch)
    if config_path is None:
        return env
    env["GIT_CONFIG_SYSTEM"] = str(config_path)
    return append_git_config_pair(env, f"branch.{branch}.remote", ".")


def write_agent_self_tracking_config(repo_root: Path, branch: str) -> Path | None:
    git_dir = current_git_dir(repo_root)
    if git_dir is None:
        return None
    config_path = git_dir / AGENT_SELF_TRACKING_CONFIG_NAME
    lines = ["# Generated by spice for per-process agent lane self-tracking."]
    # Chain the real system config first so agents keep system-level settings;
    # GIT_CONFIG_SYSTEM replaces it, and git silently ignores a missing include.
    system_config = real_system_config_path(repo_root)
    if system_config is not None:
        lines += ["[include]", f"\tpath = {system_config}"]
    lines += [
        f'[branch "{quote_git_config_subsection(branch)}"]',
        f"\tmerge = refs/heads/{branch}",
        "",
    ]
    content = "\n".join(lines)
    try:
        if config_path.read_text(encoding="utf-8") == content:
            return config_path
    except OSError:
        pass
    config_path.write_text(content, encoding="utf-8")
    return config_path


def append_git_config_pair(
    env: Mapping[str, str], key: str, value: str
) -> dict[str, str]:
    result = dict(env)
    try:
        count = max(int(result.get("GIT_CONFIG_COUNT", "0") or "0"), 0)
    except ValueError:
        count = 0
    result[f"GIT_CONFIG_KEY_{count}"] = key
    result[f"GIT_CONFIG_VALUE_{count}"] = value
    result["GIT_CONFIG_COUNT"] = str(count + 1)
    return result


def ensure_origin_head(repo_root: Path | None) -> None:
    """Ensure ``origin/HEAD`` names origin's default branch (the sync baseline).

    Set it only when an origin remote exists and the symref is missing, so a
    deliberately repointed ``origin/HEAD`` is left untouched.
    """
    if repo_root is None:
        return
    if _git(repo_root, "remote", "get-url", "origin").returncode != 0:
        return
    if _git(repo_root, "symbolic-ref", "refs/remotes/origin/HEAD").returncode == 0:
        return
    _git(repo_root, "remote", "set-head", "origin", "--auto")


def real_system_config_path(repo_root: Path) -> str | None:
    # Ask git for the system config's own path with our override removed, so we
    # chain the genuine file. Empty system config reveals no path -> nothing to
    # preserve.
    env = {k: v for k, v in os.environ.items() if k != "GIT_CONFIG_SYSTEM"}
    completed = _git(
        repo_root, "config", "--system", "--show-origin", "--list", env=env
    )
    if completed.returncode != 0:
        return None
    for line in completed.stdout.splitlines():
        if line.startswith("file:"):
            path = line[len("file:") :].split("\t", 1)[0]
            return path or None
    return None


def quote_git_config_subsection(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def current_git_branch(repo_root: Path | None) -> str:
    if repo_root is None:
        return ""
    completed = _git(repo_root, "symbolic-ref", "--quiet", "--short", "HEAD")
    return completed.stdout.strip() if completed.returncode == 0 else ""


def current_git_dir(repo_root: Path | None) -> Path | None:
    if repo_root is None:
        return None
    completed = _git(repo_root, "rev-parse", "--absolute-git-dir")
    raw = completed.stdout.strip() if completed.returncode == 0 else ""
    return Path(raw) if raw else None


def _git(repo_root: Path, *args: str, env: Mapping[str, str] | None = None):
    import subprocess

    return subprocess.run(
        ["git", "-C", str(repo_root), *args],
        capture_output=True,
        check=False,
        text=True,
        env=dict(env) if env is not None else None,
    )
