"""Per-branch git shadow config injected into agent subprocess environments.

Agents see `branch.<name>.remote = .` so `git status` stops nagging about an
upstream the agent must never touch (sync happens at task boundaries, owned by
the task control plane). The shadow rides `GIT_CONFIG_KEY_n/VALUE_n` pairs so
nothing in the worktree changes; harness internals scrub the pairs back out
so they see real upstream config.
"""

from __future__ import annotations

import os
import subprocess
from collections.abc import Mapping
from pathlib import Path

AGENT_GIT_SHADOW_CONFIG_INDEXES_ENV = (
    "SPICE_AGENT_GIT_SHADOW_CONFIG_INDEXES"  # env-policy: allow
)
AGENT_GIT_SHADOW_CONFIG_NAME = "agent.gitconfig"


def agent_git_shadow_environment(
    repo_root: Path | None, *, base_env: Mapping[str, str] | None = None
) -> dict[str, str]:
    env = dict(os.environ if base_env is None else base_env)
    pair = agent_git_shadow_include_pair(repo_root)
    if pair is None:
        return env
    return append_git_config_pairs(env, (pair,))


def agent_git_shadow_include_pair(repo_root: Path | None) -> tuple[str, str] | None:
    branch = current_git_branch(repo_root)
    git_dir = current_git_dir(repo_root)
    config_path = current_git_path(repo_root, AGENT_GIT_SHADOW_CONFIG_NAME)
    if not branch or git_dir is None or config_path is None:
        return None
    write_agent_git_shadow_config(config_path, branch)
    return (f"includeIf.gitdir:{git_dir}.path", str(config_path))


def write_agent_git_shadow_config(config_path: Path, branch: str) -> Path:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        [
            "# Generated by spice for agent git status suppression.",
            f'[branch "{quote_git_config_subsection(branch)}"]',
            "\tremote = .",
            f"\tmerge = refs/heads/{branch}",
            "",
        ]
    )
    try:
        if config_path.read_text(encoding="utf-8") == content:
            return config_path
    except OSError:
        pass
    config_path.write_text(content, encoding="utf-8")
    return config_path


def quote_git_config_subsection(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def append_git_config_pairs(
    env: Mapping[str, str], pairs: tuple[tuple[str, str], ...]
) -> dict[str, str]:
    result = dict(env)
    if not pairs:
        return result
    start = git_config_count(result)
    indexes: list[str] = []
    for offset, (key, value) in enumerate(pairs):
        index = start + offset
        result[f"GIT_CONFIG_KEY_{index}"] = key
        result[f"GIT_CONFIG_VALUE_{index}"] = value
        indexes.append(str(index))
    result["GIT_CONFIG_COUNT"] = str(start + len(pairs))
    existing = result.get(AGENT_GIT_SHADOW_CONFIG_INDEXES_ENV, "")
    result[AGENT_GIT_SHADOW_CONFIG_INDEXES_ENV] = ",".join(
        item for item in [existing, ",".join(indexes)] if item
    )
    return result


def scrub_agent_git_shadow_environment(env: Mapping[str, str]) -> dict[str, str]:
    result = dict(env)
    raw_indexes = result.pop(AGENT_GIT_SHADOW_CONFIG_INDEXES_ENV, "")
    indexes = parse_git_config_indexes(raw_indexes)
    if not indexes:
        return result
    count = git_config_count(result)
    kept_pairs: list[tuple[str, str]] = []
    for index in range(count):
        key = result.pop(f"GIT_CONFIG_KEY_{index}", None)
        value = result.pop(f"GIT_CONFIG_VALUE_{index}", None)
        if index in indexes:
            continue
        if key is not None and value is not None:
            kept_pairs.append((key, value))
    if kept_pairs:
        result["GIT_CONFIG_COUNT"] = str(len(kept_pairs))
        for index, (key, value) in enumerate(kept_pairs):
            result[f"GIT_CONFIG_KEY_{index}"] = key
            result[f"GIT_CONFIG_VALUE_{index}"] = value
    else:
        result.pop("GIT_CONFIG_COUNT", None)
    return result


def parse_git_config_indexes(raw: str) -> set[int]:
    indexes: set[int] = set()
    for item in raw.split(","):
        if not item:
            continue
        try:
            indexes.add(int(item))
        except ValueError:
            continue
    return indexes


def git_config_count(env: Mapping[str, str]) -> int:
    try:
        count = int(env.get("GIT_CONFIG_COUNT", "0") or "0")
    except ValueError:
        return 0
    return max(count, 0)


def current_git_branch(repo_root: Path | None) -> str:
    if repo_root is None:
        return ""
    completed = subprocess.run(
        ["git", "-C", str(repo_root), "symbolic-ref", "--quiet", "--short", "HEAD"],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        return ""
    return completed.stdout.strip()


def current_git_dir(repo_root: Path | None) -> Path | None:
    if repo_root is None:
        return None
    completed = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "--absolute-git-dir"],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        return None
    raw_path = completed.stdout.strip()
    return Path(raw_path) if raw_path else None


def current_git_path(repo_root: Path | None, path: str) -> Path | None:
    if repo_root is None:
        return None
    completed = subprocess.run(
        [
            "git",
            "-C",
            str(repo_root),
            "rev-parse",
            "--path-format=absolute",
            "--git-path",
            path,
        ],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        return None
    raw_path = completed.stdout.strip()
    return Path(raw_path) if raw_path else None
