"""Worktree-bound agent identity, state, environment, and skill materialization."""

from __future__ import annotations

import json
import os
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterator, Sequence

from spice.agent.driver import (
    claude_auto_compact_environment,
    driver_for,
    select_driver,
)
from spice.agent.identity import (
    ambient_thread,
    ambient_thread_id,
    canonical_thread_id,
)
from spice.agent.paths import (
    agent_state_dir,
    agent_thread_state_dir,
    agent_worktree_state_dir,
    write_agent_thread_pointer,
)
from spice.agent.shadow import shadow_environment
from spice.agent.shellhook import apply_shell_steering_environment
from spice.errors import SpiceError
from spice.locking import bounded_exclusive_lock
from spice.paths import atomic_write_json, atomic_write_text
from spice.process.git import git_probe
from spice.process.groups import process_group_is_running, process_id_is_running

# The one skill location: the standard agent-skills path, in every worktree.
# The launch prompt must link a file inside the agent's own worktree: an
# absolute path into another checkout follows that checkout's edits and
# reinstalls, which is exactly the cross-worktree trust failure this module
# exists to prevent. Spice keeps generated copies fresh from the packaged
# source while keeping them ignored by the target repo.
WORKTREE_SKILL_RELATIVE_PATH = Path(".agents") / "skills" / "spice" / "SKILL.md"
WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH = (
    WORKTREE_SKILL_RELATIVE_PATH.parent / ".gitignore"
)
WORKTREE_SKILL_GITIGNORE_CONTENT = (
    "# Autogenerated by spice; do not edit.\n"
    "# This directory holds the generated worktree-bound agent skill copy.\n"
    "# Edit the packaged spice skill source instead of files in this directory.\n"
    "/.gitignore\n"
    "/SKILL.md\n"
)
PACKAGED_SKILL_RESOURCE = ("spice.agent", "SKILL.md")
AGENT_STATE_FILE = "state.json"
AGENT_LOCK_FILE = "ensure.lock"
AGENT_STARTUP_STARTING = "starting"
AGENT_STARTUP_READY = "ready"
AGENT_STARTUP_STALLED = "startup-stalled"
SUPERVISOR_ENVIRONMENT_SCRUB_NAMES = (
    "VIRTUAL_ENV",
    "UV_PROJECT_ENVIRONMENT",
)
AGENT_ENSURE_LOCK_TIMEOUT_SECONDS = 10.0
# This is an operator diagnostic, not a process-kill deadline. Two ordinary
# claim-renewal intervals give quiet tool work room while still surfacing a
# wedged lane well before its one-hour claim expires.
AGENT_OUTPUT_STALL_SECONDS = 30.0 * 60.0


@dataclass(frozen=True)
class AgentStatus:
    repo_root: Path
    state_path: Path
    process_status: str
    pid: int | None
    process_group_id: int | None
    thread_id: str
    driver: str
    model: str
    reasoning_effort: str
    service_tier: str
    started_at: str
    ready_at: str
    startup_failure: str
    log_path: Path | None
    prompt_skill_path: Path | None
    command: tuple[str, ...]

    @property
    def running(self) -> bool:
        return self.process_status in {"starting", "running", "stopping"}

    @property
    def ready(self) -> bool:
        return self.process_status == "running"


@dataclass(frozen=True)
class AgentOutputObservation:
    status: str
    source: str
    path: Path | None
    last_output_at: str
    age_seconds: int | None


def agent_status(repo_root: Path) -> AgentStatus:
    resolved_root = repo_root.resolve()
    state = read_agent_state(resolved_root)
    agent_state = state if agent_state_is_authoritative(state) else {}
    pid = state_int(agent_state.get("pid"))
    pgid = state_int(agent_state.get("process_group_id")) or pid
    running = process_id_is_running(pid) and process_group_is_running(pgid)
    thread_id = canonical_thread_id(agent_state.get("thread_id"))
    skill_path = state_path_value(agent_state.get("prompt_skill_path"))
    if skill_path is None:
        skill_path = available_skill_path(resolved_root, required=False)
    command = state_command_value(agent_state.get("command"))
    return AgentStatus(
        repo_root=resolved_root,
        state_path=agent_state_path(resolved_root),
        process_status=agent_process_status(
            running=running, state=agent_state, thread_id=thread_id
        ),
        pid=pid,
        process_group_id=pgid,
        thread_id=thread_id,
        driver=str(agent_state.get("driver") or ""),
        model=str(agent_state.get("model") or ""),
        reasoning_effort=str(agent_state.get("reasoning_effort") or ""),
        service_tier=str(agent_state.get("service_tier") or ""),
        started_at=str(agent_state.get("started_at") or ""),
        ready_at=str(agent_state.get("ready_at") or ""),
        startup_failure=str(agent_state.get("startup_failure") or ""),
        log_path=state_path_value(agent_state.get("log_path")),
        prompt_skill_path=skill_path,
        command=command,
    )


def agent_output_observation(
    status: Any, *, now: datetime | None = None
) -> AgentOutputObservation | None:
    """Measure a running agent's output recency from driver-owned artifacts."""
    if str(getattr(status, "process_status", "") or "") != "running":
        return None
    path, source = _agent_output_path(status)
    reference = now or datetime.now(UTC)
    if reference.tzinfo is None:
        reference = reference.replace(tzinfo=UTC)
    if path is not None:
        try:
            observed_epoch = path.stat().st_mtime
        except OSError:
            path = None
            source = ""
        else:
            return _output_observation(
                source=source,
                path=path,
                observed_epoch=observed_epoch,
                reference=reference,
            )
    started_epoch = _timestamp_epoch(str(getattr(status, "started_at", "") or ""))
    if started_epoch is None:
        return AgentOutputObservation("unknown", "", None, "", None)
    observation = _output_observation(
        source="none",
        path=None,
        observed_epoch=started_epoch,
        reference=reference,
    )
    return AgentOutputObservation(
        observation.status,
        observation.source,
        observation.path,
        "",
        observation.age_seconds,
    )


def _agent_output_path(status: Any) -> tuple[Path | None, str]:
    thread_id = canonical_thread_id(getattr(status, "thread_id", ""))
    repo_root = Path(getattr(status, "repo_root", Path.cwd())).expanduser().resolve()
    if thread_id:
        driver_name = str(getattr(status, "driver", "") or "")
        try:
            driver = (
                select_driver(driver_name) if driver_name else driver_for(repo_root)
            )
            transcript = driver.thread_transcript_path(thread_id)
        except (OSError, SpiceError, SystemExit):
            pass
        else:
            if transcript.is_file():
                return transcript, "transcript"
    log_path = state_path_value(getattr(status, "log_path", None))
    if log_path is not None and log_path.is_file():
        return log_path.resolve(), "log"
    return None, ""


def _output_observation(
    *,
    source: str,
    path: Path | None,
    observed_epoch: float,
    reference: datetime,
) -> AgentOutputObservation:
    age_seconds = max(0, int(reference.timestamp() - observed_epoch))
    output_status = "stalled" if age_seconds >= AGENT_OUTPUT_STALL_SECONDS else "active"
    observed_at = (
        datetime.fromtimestamp(observed_epoch, UTC)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )
    return AgentOutputObservation(
        output_status,
        source,
        path,
        observed_at,
        age_seconds,
    )


def _timestamp_epoch(value: str) -> float | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()
    except ValueError:
        return None


def agent_binding_error(repo_root: Path, status: Any) -> str:
    expected_root = repo_root.expanduser().resolve()
    status_root = (
        Path(getattr(status, "repo_root", expected_root) or expected_root)
        .expanduser()
        .resolve()
    )
    if status_root != expected_root:
        return (
            "agent binding mismatch: status root "
            f"{status_root} != lane root {expected_root}"
        )
    command_cwd = agent_command_cwd(getattr(status, "command", ()))
    command_root = command_cwd.expanduser().resolve() if command_cwd else None
    if command_root is not None and command_root != expected_root:
        return (
            "agent binding mismatch: launch cwd "
            f"{command_root} != lane root {expected_root}"
        )
    return ""


def agent_command_cwd(command: Sequence[str]) -> Path | None:
    args = list(command)
    for index, part in enumerate(args[:-1]):
        if part == "--cd":
            return Path(args[index + 1])
    return None


@contextmanager
def agent_ensure_lock(
    repo_root: Path, *, timeout_seconds: float = AGENT_ENSURE_LOCK_TIMEOUT_SECONDS
) -> Iterator[None]:
    lock_path = agent_worktree_state_dir(repo_root) / AGENT_LOCK_FILE
    with bounded_exclusive_lock(
        lock_path,
        timeout_seconds=timeout_seconds,
        action="ensure agent lifecycle",
    ):
        yield


def available_skill_path(
    repo_root: Path, *, required: bool, packaged_path: Path | None = None
) -> Path | None:
    """The spice skill, always inside ``repo_root``.

    The materialized (or repo-owned) worktree file is the only runtime path.
    The packaged skill is only a source for writing that file into the tree.
    """
    materialized = materialize_worktree_skill(repo_root, packaged_path=packaged_path)
    if materialized is not None:
        return materialized
    if required:
        raise SpiceError(f"missing spice skill at {worktree_skill_path(repo_root)}")
    return None


def worktree_skill_path(repo_root: Path) -> Path:
    return (repo_root / WORKTREE_SKILL_RELATIVE_PATH).expanduser().resolve()


def worktree_skill_gitignore_path(repo_root: Path) -> Path:
    return (repo_root / WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH).expanduser().resolve()


def materialize_worktree_skill(
    repo_root: Path, *, packaged_path: Path | None = None
) -> Path | None:
    """The worktree's skill file, kept fresh; None when the tree can't hold one.

    The file is rewritten whenever it drifts from the packaged source, so
    reinstalling spice updates every ignored worktree copy on its next
    activation or launch. A tracked worktree copy is returned without rewriting,
    because Git cannot ignore tracked-file modifications.
    """
    target = worktree_skill_path(repo_root)
    packaged = packaged_path or packaged_skill_path()
    if not packaged.is_file():
        if target.is_file():
            materialize_worktree_skill_gitignore(repo_root)
            return target
        return None
    content = packaged.read_text(encoding="utf-8")
    try:
        materialize_worktree_skill_gitignore(repo_root)
        if target.is_file():
            if target.read_text(encoding="utf-8") == content:
                return target
            if git_tracks_relative_path(repo_root, WORKTREE_SKILL_RELATIVE_PATH):
                return target
        atomic_write_text(target, content, write_if_changed=True)
    except OSError:
        return target if target.is_file() else None
    return target


def materialize_worktree_skill_gitignore(repo_root: Path) -> Path | None:
    """Write the generated skill directory ignore file when possible."""
    target = worktree_skill_gitignore_path(repo_root)
    try:
        if target.is_file():
            if target.read_text(encoding="utf-8") == WORKTREE_SKILL_GITIGNORE_CONTENT:
                return target
            if git_tracks_relative_path(
                repo_root, WORKTREE_SKILL_GITIGNORE_RELATIVE_PATH
            ):
                return target
        atomic_write_text(
            target, WORKTREE_SKILL_GITIGNORE_CONTENT, write_if_changed=True
        )
    except OSError:
        return target if target.is_file() else None
    return target


def git_tracks_relative_path(repo_root: Path, relative_path: Path) -> bool:
    """Whether Git already tracks ``relative_path`` in ``repo_root``."""
    result = git_probe(
        repo_root, "ls-files", "--error-unmatch", "--", relative_path.as_posix()
    )
    return result.returncode == 0


def packaged_skill_path() -> Path:
    return Path(__file__).resolve().parent / PACKAGED_SKILL_RESOURCE[1]


def agent_state_path(repo_root: Path) -> Path:
    return agent_state_dir(repo_root) / AGENT_STATE_FILE


def read_agent_state(repo_root: Path) -> dict[str, Any]:
    path = agent_state_path(repo_root)
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def write_agent_state(repo_root: Path, state: dict[str, Any]) -> None:
    thread_id = canonical_thread_id(state.get("thread_id"))
    if thread_id:
        path = agent_thread_state_dir(repo_root, thread_id) / AGENT_STATE_FILE
    else:
        path = agent_state_path(repo_root)
    atomic_write_json(path, state)
    if thread_id:
        write_agent_thread_pointer(repo_root, thread_id)


def agent_state_is_authoritative(state: dict[str, Any]) -> bool:
    return all(
        str(state.get(key) or "") for key in ("mode", "started_at", "prompt_skill_path")
    )


def settle_agent_log_path(repo_root: Path, log_path: Path, thread_id: str) -> Path:
    canonical = canonical_thread_id(thread_id)
    if not canonical:
        return log_path
    target = agent_thread_state_dir(repo_root, canonical) / "logs" / log_path.name
    if log_path == target:
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        log_path.replace(target)
    except FileNotFoundError:
        return target
    return target


def state_int(value: Any) -> int | None:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def state_path_value(value: Any) -> Path | None:
    if not value:
        return None
    return Path(str(value)).expanduser()


def state_command_value(value: Any) -> tuple[str, ...]:
    if not isinstance(value, list):
        return ()
    return tuple(item for item in value if isinstance(item, str))


def agent_process_status(
    *, running: bool, state: dict[str, Any], thread_id: str
) -> str:
    if running:
        startup_status = str(state.get("startup_status") or "")
        if startup_status == AGENT_STARTUP_STARTING:
            return "starting"
        if startup_status == AGENT_STARTUP_STALLED:
            return "stopping"
        return "running"
    if not state:
        return "unstarted"
    if str(state.get("startup_status") or "") == AGENT_STARTUP_STALLED:
        return AGENT_STARTUP_STALLED
    return "idle" if thread_id else "stopped"


def agent_environment(repo_root: Path | None = None) -> dict[str, str]:
    ambient = ambient_thread()
    if ambient is not None:
        _thread_id, driver = ambient
        raise SpiceError(
            f"refusing to spawn an agent with ambient {driver.thread_id_env} set; "
            f"unset {driver.thread_id_env} before starting spice serve or "
            "agent ensure"
        )
    # Mask the agent's upstream to its own lane (per-process, env-only) so its
    # status never moves when origin advances; the operator's own shell has no
    # such env and keeps native branch config untouched.
    env = shadow_environment(repo_root)
    if repo_root is not None:
        env = apply_shell_steering_environment(repo_root, base_env=env)
        env.update(claude_auto_compact_environment(repo_root, base_env=env))
    return env


def agent_supervisor_environment(repo_root: Path | None = None) -> dict[str, str]:
    env = agent_environment(repo_root)
    for name in SUPERVISOR_ENVIRONMENT_SCRUB_NAMES:
        env.pop(name, None)
    env["GIT_EDITOR"] = "true"
    return env


def utc_now() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds").replace("+00:00", "Z")


def bind_ambient_agent_thread(repo_root: Path) -> AgentStatus:
    """Bind this worktree to the driver thread id ambient in this process.

    Driven from the hook points that already run on ordinary agent traffic --
    the driver's post-tool hook and the `spice agent run` shell stage -- as
    well as from `spice agent activation`. A worktree therefore learns its
    session id from the first command an agent runs in it, instead of from a
    bootstrap step the agent has to remember to perform. All three paths share
    this one function so they write identical state.

    Re-binding the thread already recorded is a no-op: the hook points fire on
    every command, and rewriting unchanged state on each one would churn the
    state file for nothing.
    """
    ambient = ambient_thread_id()
    if not ambient:
        return agent_status(repo_root)
    state = read_agent_state(repo_root)
    if canonical_thread_id(state.get("thread_id")) == ambient:
        return agent_status(repo_root)
    if agent_state_is_authoritative(state):
        state["thread_id"] = ambient
    else:
        prompt_skill_path = available_skill_path(repo_root, required=False)
        state = {
            "pid": os.getpid(),
            "process_group_id": os.getpgrp(),
            "started_at": utc_now(),
            "mode": "bind",
            "command": [],
            "driver": driver_for(repo_root).name,
            "model": "",
            "reasoning_effort": "",
            "service_tier": "",
            "thread_id": ambient,
            "prompt_skill_path": str(prompt_skill_path or ""),
            "log_path": "",
        }
    write_agent_state(repo_root, state)
    return agent_status(repo_root)


def _carry_team_membership(predecessor: str, successor: str, driver: str = "") -> None:
    """Move the predecessor's team slot to the imported thread (a renewal).

    An import is a renewal of whoever this worktree was bound to: the imported
    thread should inherit the predecessor's team membership so team-scoped
    allocation keeps seeing it. Reuses the store's alias slot-transfer --
    assign_agent with the predecessor as an alias deletes the predecessor's
    membership and seats the successor in the same slot, so the team neither
    grows nor recharges its ceiling. A no-op when there is no predecessor, it is
    the same thread, the successor already holds a slot, or the predecessor was
    on no team. A fresh worktree with no locally-bound predecessor (the fork
    case) has nothing to resolve here on its own -- ``import_agent``'s
    ``predecessor_thread`` parameter (``spice agent import --from``) supplies
    that lineage explicitly instead.
    """
    if not predecessor or predecessor == successor:
        return
    from spice.serve.team.store import ServeTeamStore

    store = ServeTeamStore()
    for team in store.team_snapshot().teams:
        member_ids = [member.agent_id for member in team.members]
        if successor in member_ids:
            return
        if predecessor in member_ids:
            store.assign_agent(team.team_id, successor, aliases=[predecessor])
            _carry_member_driver(store, predecessor, successor, driver)
            return


def _carry_member_driver(
    store: Any, predecessor: str, successor: str, driver: str
) -> None:
    """Record the imported driver on the successor, keeping the renewal's config.

    Carries the predecessor's model/effort/target (an import is a renewal) but
    sets both drivers to the imported worktree's driver, so the team member reads
    back as the agent that was actually imported. The driver cannot be recovered
    from the UUID -- it predates the identity and is determined per worktree.
    """
    if not driver:
        return
    prior = store.agent_identity_for_actor(predecessor)
    store.record_agent_identity(
        actor_id=successor,
        target_id=prior.target_id if prior else "",
        thread_id=successor,
        actual_driver=driver,
        actual_model=prior.actual_model if prior else "",
        actual_effort=prior.actual_effort if prior else "",
        actual_service_tier=prior.actual_service_tier if prior else "",
        desired_driver=driver,
        desired_model=prior.desired_model if prior else "",
        desired_effort=prior.desired_effort if prior else "",
        transcript_owner=successor,
    )
