"""The per-process git shadow environment, injected for agent processes only.

An agent's branch should track *itself* so its ``git status`` never moves when
origin advances — but the operator working in the same repo must still see the
real upstream. So the shadow is environment-only (never written to shared
config):

* ``GIT_CONFIG_SYSTEM`` points git at a generated per-lane file holding
  ``branch.<lane>.merge = refs/heads/<lane>``. System config is read *first*, and
  ``@{upstream}`` uses the *first* ``branch.merge`` value, so the agent's upstream
  resolves to itself. (The native ``merge`` stays last, so ``git config --get``
  still returns the real branch — the control plane reads truth.)
* a command-scope ``branch.<lane>.remote=.`` pair (read *last*, where ``remote``
  is resolved) completes the self-reference.

The operator runs without these vars and sees the real upstream untouched. The
task control plane reads the integration branch with ``git config --get`` (see
``spice.tasks.gitsync``), which returns the native worktree value despite the
system-scope self merge, so it needs no scrubbing.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path

AGENT_GITCONFIG_NAME = "agent.gitconfig"


def shadow_environment(
    repo_root: Path | None, *, base_env: Mapping[str, str] | None = None
) -> dict[str, str]:
    env = dict(os.environ if base_env is None else base_env)
    branch = current_git_branch(repo_root)
    if repo_root is None or not branch:
        return env
    config_path = write_shadow_config(repo_root, branch)
    if config_path is None:
        return env
    env["GIT_CONFIG_SYSTEM"] = str(config_path)
    return append_git_config_pair(env, f"branch.{branch}.remote", ".")


def write_shadow_config(repo_root: Path, branch: str) -> Path | None:
    git_dir = current_git_dir(repo_root)
    if git_dir is None:
        return None
    config_path = git_dir / AGENT_GITCONFIG_NAME
    # Chain the real system config first so agents keep system-level settings;
    # GIT_CONFIG_SYSTEM replaces it. Bake in the detected path (works across
    # /etc, Homebrew, Xcode layouts), falling back to the conventional default;
    # git silently ignores the include when the file is missing.
    system_config = real_system_config_path(repo_root) or "/etc/gitconfig"
    lines = [
        "# Generated by spice for the per-process agent git shadow.",
        "[include]",
        f"\tpath = {system_config}",
    ]
    lines += [
        f'[branch "{quote_git_config_subsection(branch)}"]',
        f"\tmerge = refs/heads/{branch}",
        "",
    ]
    content = "\n".join(lines)
    try:
        if config_path.read_text(encoding="utf-8") == content:
            return config_path
    except OSError:
        pass
    config_path.write_text(content, encoding="utf-8")
    return config_path


def append_git_config_pair(
    env: Mapping[str, str], key: str, value: str
) -> dict[str, str]:
    result = dict(env)
    try:
        count = max(int(result.get("GIT_CONFIG_COUNT", "0") or "0"), 0)
    except ValueError:
        count = 0
    for index in range(count):
        # Idempotent: re-applying to an env that already carries the shadow must
        # not duplicate the command-scope remote pair.
        if (
            result.get(f"GIT_CONFIG_KEY_{index}") == key
            and result.get(f"GIT_CONFIG_VALUE_{index}") == value
        ):
            return result
    result[f"GIT_CONFIG_KEY_{count}"] = key
    result[f"GIT_CONFIG_VALUE_{count}"] = value
    result["GIT_CONFIG_COUNT"] = str(count + 1)
    return result


def ensure_origin_head(repo_root: Path | None) -> None:
    """Ensure ``origin/HEAD`` names origin's default branch (the baseline fallback).

    Set it only when an origin remote exists and the symref is missing, so a
    deliberately repointed ``origin/HEAD`` is left untouched.
    """
    if repo_root is None:
        return
    if _git(repo_root, "remote", "get-url", "origin").returncode != 0:
        return
    if _git(repo_root, "symbolic-ref", "refs/remotes/origin/HEAD").returncode == 0:
        return
    _git(repo_root, "remote", "set-head", "origin", "--auto")


def real_system_config_path(repo_root: Path) -> str | None:
    # `git config --system --edit` invokes $GIT_EDITOR on the system config
    # file, so a no-op editor (echo) prints git's compile-time system path even
    # when that file is empty or absent — and does not modify it. Query with our
    # GIT_CONFIG_SYSTEM override removed so we get git's genuine default.
    env = {k: v for k, v in os.environ.items() if k != "GIT_CONFIG_SYSTEM"}
    env["GIT_EDITOR"] = "echo"
    completed = _git(repo_root, "config", "--system", "--edit", env=env)
    if completed.returncode != 0:
        return None
    return completed.stdout.strip() or None


def quote_git_config_subsection(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def current_git_branch(repo_root: Path | None) -> str:
    if repo_root is None:
        return ""
    completed = _git(repo_root, "symbolic-ref", "--quiet", "--short", "HEAD")
    return completed.stdout.strip() if completed.returncode == 0 else ""


def current_git_dir(repo_root: Path | None) -> Path | None:
    if repo_root is None:
        return None
    completed = _git(repo_root, "rev-parse", "--absolute-git-dir")
    raw = completed.stdout.strip() if completed.returncode == 0 else ""
    return Path(raw) if raw else None


def _git(repo_root: Path, *args: str, env: Mapping[str, str] | None = None):
    import subprocess

    return subprocess.run(
        ["git", "-C", str(repo_root), *args],
        capture_output=True,
        check=False,
        text=True,
        env=dict(env) if env is not None else None,
    )
