"""Generated shell startup hooks for agent side-channel steering."""

from __future__ import annotations

import shlex
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

from spice.paths import atomic_write_text, state_dir

ZDOTDIR_ENV = "ZDOTDIR"
BASH_ENV_ENV = "BASH_ENV"
SHELL_HOOK_DIRNAME = "shell-hook"
BASH_HOOK_NAME = "bash_env"
ZSH_HOOK_NAMES = (".zshenv", ".zprofile", ".zlogin")


def apply_shell_steering_environment(
    repo_root: Path,
    *,
    driver_state_dirname: str,
    base_env: Mapping[str, str],
) -> dict[str, str]:
    env = dict(base_env)
    hook_dir = write_shell_steering_files(
        repo_root,
        driver_state_dirname=driver_state_dirname,
        base_env=env,
    )
    env[ZDOTDIR_ENV] = str(hook_dir)
    env[BASH_ENV_ENV] = str(hook_dir / BASH_HOOK_NAME)
    return env


def write_shell_steering_files(
    repo_root: Path,
    *,
    driver_state_dirname: str,
    base_env: Mapping[str, str],
    python_command: Sequence[str] | None = None,
) -> Path:
    resolved_root = repo_root.expanduser().resolve()
    hook_dir = shell_steering_hook_dir(
        resolved_root, driver_state_dirname=driver_state_dirname
    )
    hook_dir.mkdir(parents=True, exist_ok=True)
    agent_run_command = [
        *(python_command or (sys.executable,)),
        "-m",
        "spice",
        "agent",
        "run",
        "--",
    ]
    real_zdotdir = real_zdotdir_path(base_env)
    original_zdotdir = base_env.get(ZDOTDIR_ENV, "")
    original_bash_env = base_env.get(BASH_ENV_ENV, "")
    for name in ZSH_HOOK_NAMES:
        path = hook_dir / name
        atomic_write_text(
            path,
            render_shell_steering_hook(
                agent_run_command=agent_run_command,
                restore_lines=[
                    restore_env_line(ZDOTDIR_ENV, original_zdotdir),
                    restore_env_line(BASH_ENV_ENV, original_bash_env),
                ],
                real_source_path=real_zdotdir / name,
                self_path=path,
            ),
        )
    bash_hook = hook_dir / BASH_HOOK_NAME
    real_bash_env = Path(original_bash_env).expanduser() if original_bash_env else None
    atomic_write_text(
        bash_hook,
        render_shell_steering_hook(
            agent_run_command=agent_run_command,
            restore_lines=[
                restore_env_line(ZDOTDIR_ENV, original_zdotdir),
                restore_env_line(BASH_ENV_ENV, original_bash_env),
            ],
            real_source_path=real_bash_env,
            self_path=bash_hook,
        ),
    )
    return hook_dir


def shell_steering_hook_dir(repo_root: Path, *, driver_state_dirname: str) -> Path:
    return state_dir(repo_root) / "agents" / driver_state_dirname / SHELL_HOOK_DIRNAME


def real_zdotdir_path(base_env: Mapping[str, str]) -> Path:
    if raw := base_env.get(ZDOTDIR_ENV):
        return Path(raw).expanduser()
    if home := base_env.get("HOME"):
        return Path(home).expanduser()
    return Path.home()


def restore_env_line(name: str, value: str) -> str:
    if value:
        return f"export {name}={shell_quote(value)}"
    return f"unset {name}"


def render_shell_steering_hook(
    *,
    agent_run_command: Sequence[str],
    restore_lines: Sequence[str],
    real_source_path: Path | None,
    self_path: Path,
) -> str:
    lines = [
        "# Generated by spice; do not edit.",
        *agent_run_reexec_lines(
            agent_run_command=agent_run_command,
            restore_lines=restore_lines,
        ),
        *restore_lines,
    ]
    if real_source_path is not None:
        source = shell_quote(str(real_source_path))
        self_file = shell_quote(str(self_path))
        lines.extend(
            [
                f"if [ -r {source} ] && [ {source} != {self_file} ]; then",
                f"  . {source}",
                "fi",
            ]
        )
    return "\n".join(lines) + "\n"


def agent_run_reexec_lines(
    *, agent_run_command: Sequence[str], restore_lines: Sequence[str]
) -> list[str]:
    command = shell_command(agent_run_command)
    restored = [f"  {line}" for line in restore_lines]
    return [
        'if [ -n "${ZSH_EXECUTION_STRING-}" ]; then',
        *restored,
        '  _spice_shell_bin="${SHELL:-${ZSH_NAME:-zsh}}"',
        '  case "$_spice_shell_bin" in',
        "    *zsh) ;;",
        '    *) _spice_shell_bin="${ZSH_NAME:-zsh}" ;;',
        "  esac",
        '  if ! command -v "$_spice_shell_bin" >/dev/null 2>&1; then',
        (
            '    printf "%s\\n" '
            '"spice shell hook: cannot resolve zsh for agent-run reexec" >&2'
        ),
        "    exit 127",
        "  fi",
        "  if [[ -o login ]]; then",
        f'    exec {command} "$_spice_shell_bin" -lc "$ZSH_EXECUTION_STRING"',
        ('    printf "%s\\n" "spice shell hook: failed to exec agent run" >&2'),
        "    exit 127",
        "  fi",
        f'  exec {command} "$_spice_shell_bin" -c "$ZSH_EXECUTION_STRING"',
        '  printf "%s\\n" "spice shell hook: failed to exec agent run" >&2',
        "  exit 127",
        "fi",
        'if [ -n "${BASH_EXECUTION_STRING-}" ]; then',
        *restored,
        '  _spice_shell_bin="${BASH:-bash}"',
        '  if ! command -v "$_spice_shell_bin" >/dev/null 2>&1; then',
        (
            '    printf "%s\\n" '
            '"spice shell hook: cannot resolve bash for agent-run reexec" >&2'
        ),
        "    exit 127",
        "  fi",
        "  if shopt -q login_shell; then",
        f'    exec {command} "$_spice_shell_bin" -lc "$BASH_EXECUTION_STRING"',
        ('    printf "%s\\n" "spice shell hook: failed to exec agent run" >&2'),
        "    exit 127",
        "  fi",
        f'  exec {command} "$_spice_shell_bin" -c "$BASH_EXECUTION_STRING"',
        '  printf "%s\\n" "spice shell hook: failed to exec agent run" >&2',
        "  exit 127",
        "fi",
        "case $- in",
        "  *i*) ;;",
        "  *)",
        (
            '    printf "%s\\n" '
            '"spice shell hook: cannot agent-run reexec noninteractive shell '
            'without an execution string" >&2'
        ),
        "    exit 127",
        "    ;;",
        "esac",
    ]


def shell_command(command: Sequence[str]) -> str:
    return " ".join(shell_quote(part) for part in command)


def shell_quote(value: str) -> str:
    return shlex.quote(value)
